# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3Aju4n0tbmO3SoeTs97EKUcd_nDjHo9

The Sample Superstore Dataset contains transactional data of a retail business, including details such as sales, profit, customer segments, regions, product categories, and discounts.

The objective of this analysis is to explore the dataset and identify key business insights that can help improve overall performance. The analysis focuses on understanding sales trends, profit distribution, customer behavior, and the impact of discounts on profitability.





1.   Packages Import
2.   data ingestion
"""

#packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#data ingestion
df = pd.read_csv('/content/SampleSuperstore.csv')

#data show of
df.head(5)

#data information
df.info()

"""## 📊 Dataset Overview Summary

The Sample Superstore dataset consists of **9,994 records** and **13 columns**, representing transactional data of a retail business. Each row corresponds to an individual sales transaction.

### 🔹 Data Structure

* Total Entries: **9994**
* Total Columns: **13**
* Memory Usage: **~1015 KB**

### 🔹 Data Types

* **Object (Categorical Data): 8 columns**
  These include:

  * Ship Mode
  * Segment
  * Country
  * City
  * State
  * Region
  * Category
  * Sub-Category

  👉 These columns help in grouping and analyzing business performance across different dimensions.

* **Integer (Numerical Data): 2 columns**

  * Postal Code
  * Quantity

  👉 Quantity represents the number of items sold per transaction.

* **Float (Continuous Numerical Data): 3 columns**

  * Sales
  * Discount
  * Profit

  👉 These are the most important columns for financial analysis.

### 🔹 Data Quality

* All columns have **9994 non-null values**, indicating:
  ✅ No missing values
  ✅ Clean dataset ready for analysis

### 🔹 Key Insights About the Data

* The dataset includes both **categorical and numerical features**, making it suitable for detailed analysis.
* It allows analysis across multiple dimensions such as:

  * Geography (City, State, Region)
  * Customer Segments
  * Product Categories
* Financial performance can be evaluated using:

  * Sales
  * Profit
  * Discount

### 🔹 Conclusion

The dataset is well-structured and clean, with no missing values. It provides sufficient information to perform exploratory data analysis (EDA), identify trends, and generate actionable business insights related to sales performance, profitability, and customer behavior.

"""

#Basic overview
print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())
print("Total Orders:", df.shape[0])
print("Average Sales:", df["Sales"].mean())

"""The analysis of the dataset provides an overview of the business performance through key metrics such as total sales, total profit, number of orders, and average sales per order.

Total Sales represents the overall revenue generated from all transactions, indicating the scale of business operations.

Total Profit shows the net earnings after accounting for costs and discounts, helping evaluate overall profitability.

Total Orders indicates the volume of transactions, reflecting customer activity and demand.

Average Sales gives insight into the typical value of each order, helping understand customer purchasing behavior.
"""

#Category analysis
category_analysis = df.groupby("Category")[["Sales", "Profit"]].sum()
print(category_analysis)

"""📊 Category Analysis Summary

This analysis groups the data by Category and calculates the total Sales and Profit for each category.

It provides a high-level view of how each category contributes to overall revenue and profitability.

It helps identify the most profitable category as well as categories that may have lower profit margins.

By comparing sales and profit together, it becomes easier to understand whether high sales are translating into actual profit.
"""

#Sub-category analysis
subcat_analysis = df.groupby("Sub-Category")[["Sales", "Profit"]].sum().sort_values(by="Sales", ascending=False)
print(subcat_analysis)

"""📊 Sub-Category Analysis Summary
This analysis groups the data by Sub-Category and calculates the total Sales and Profit for each, sorted by highest sales.

It helps identify top-performing sub-categories that generate the most revenue.

It also highlights profitability, showing which products contribute most to earnings.

Some sub-categories may show high sales but low or negative profit, indicating potential issues like high discounts or costs.

"""

#Region analysis
region_analysis = df.groupby("Region")[["Sales", "Profit"]].sum()
print(region_analysis)

"""📊 Region Analysis Summary

This analysis groups the data by Region and calculates the total Sales and Profit for each region.

It helps identify which regions are generating the highest revenue and profit.

It also highlights regions that may be underperforming or experiencing losses.

By comparing sales and profit, it becomes easier to evaluate the overall business performance across different geographical areas.
"""

#State Analysis
state_sales = df.groupby("State")["Sales"].sum().sort_values(ascending=False).head(10)
print(state_sales)

"""📊 Top States by Sales Summary

This analysis identifies the top 10 states based on total Sales, sorted in descending order.

It highlights the states that contribute the highest revenue to the business.

These states represent key markets where demand is strong and business performance is high.

Focusing on these regions can help in maximizing sales and expanding market presence.
"""

#Segment analysis
segment_analysis = df.groupby("Segment")[["Sales", "Profit"]].sum()
print(segment_analysis)

"""📊 Segment Analysis Summary

This analysis groups the data by Customer Segment and calculates total Sales and Profit for each segment.

It helps identify which customer segment contributes the most to revenue and profitability.

It provides insights into customer behavior and purchasing patterns across segments.

By comparing sales and profit, it becomes easier to determine the most valuable customer group for the business.
"""

#Discount impact
discount_analysis = df.groupby("Discount")["Profit"].mean()
print(discount_analysis)

"""This analysis groups the data by Discount and calculates the average Profit for each discount level.

It helps understand how different discount rates impact profitability.

Higher discounts often result in lower or negative average profit, indicating reduced margins.

Lower or no discounts tend to maintain better profitability.
"""

#Correlation (Sales vs Profit)
correlation = df[["Sales", "Profit"]].corr()
print(correlation)

"""📊 Sales vs Profit Correlation Summary
This analysis calculates the correlation between Sales and Profit to understand their relationship.

It shows whether an increase in sales leads to an increase in profit.

A positive correlation indicates that higher sales generally result in higher profit.

A weak or negative correlation suggests that high sales do not always guarantee profitability, possibly due to factors like discounts or high costs.
"""

# Category Sales Chart
df.groupby("Category")["Sales"].sum().plot(kind="bar")
plt.title("Sales by Category")
plt.show()

# Profit by Region
df.groupby("Region")["Profit"].sum().plot(kind="bar")
plt.title("Profit by Region")
plt.show()

# Sales vs Profit Scatter
plt.scatter(df["Sales"], df["Profit"])
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.title("Sales vs Profit")
plt.show()

"""📊 Visualization Summary

The visualizations provide a clear understanding of sales distribution, regional profitability, and the relationship between sales and profit.

The Sales by Category (Bar Chart) highlights how revenue is distributed across different product categories, helping identify the highest-selling category.

The Profit by Region (Bar Chart) shows the profitability across regions, making it easy to compare performance and identify top and underperforming regions.

The Sales vs Profit (Scatter Plot) illustrates the relationship between sales and profit, helping to detect patterns such as high sales with low or negative profit.
"""

# High discount but loss
high_discount_loss = df[(df["Discount"] > 0.3) & (df["Profit"] < 0)]
print(high_discount_loss.head())

"""## 📊 High Discount but Loss Analysis Summary

This analysis filters transactions where the **discount is greater than 30%** and the **profit is negative**.

* It helps identify cases where **high discounts are leading to losses**.
* These transactions indicate that excessive discounting is negatively impacting profitability.
* It highlights the need to **optimize discount strategies** to avoid selling products at a loss.

Overall, this analysis reveals a critical business issue where higher discounts may reduce profit margins and lead to financial losses, guiding better pricing decisions.

"""

#Boxplot (Outliers Detection)
sns.boxplot(x=df["Profit"])
plt.title("Profit Distribution (Boxplot)")
plt.show()

"""📊 Profit Distribution (Boxplot) Summary

This boxplot visualizes the distribution of Profit and helps identify outliers in the dataset.

The central box represents the middle 50% of profit values (IQR).

The line inside the box shows the median profit.

Points outside the whiskers represent outliers, indicating unusually high profits or significant losses.
"""

#Average Profit by Category (Bar)
df.groupby("Category")["Profit"].mean().plot(kind="bar")
plt.title("Average Profit by Category")
plt.xlabel("Category")
plt.ylabel("Average Profit")
plt.show()

"""📊 Average Profit by Category Summary

This bar chart shows the average profit for each product category.

It helps compare how profitable each category is on average, rather than total profit.

Categories with higher average profit indicate better margin per sale.

Categories with lower or negative average profit may indicate pricing or discount issues.
"""

#Top 10 Cities by Sales
df.groupby("City")["Sales"].sum().sort_values(ascending=False).head(10).plot(kind="bar")
plt.title("Top 10 Cities by Sales")
plt.xlabel("City")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.show()

"""📊 Top 10 Cities by Sales Summary

This bar chart displays the top 10 cities based on total Sales.

It highlights the cities that generate the highest revenue for the business.

These cities represent key markets with strong customer demand.

The comparison helps identify where the company is performing best geographically.
"""

#Sales by Segment (Pie Chart)
df.groupby("Segment")["Sales"].sum().plot(kind="pie", autopct="%1.1f%%")
plt.title("Sales by Segment")
plt.ylabel("")
plt.show()

"""📊 Sales by Segment (Pie Chart) Summary

This pie chart represents the distribution of Sales across different customer segments.

It shows the percentage contribution of each segment (Consumer, Corporate, Home Office) to total sales.

Helps identify which segment generates the highest revenue share.

Provides insight into customer demand patterns across segments.
"""

# Discount vs Profit (Scatter - Clear View)
plt.scatter(df["Discount"], df["Profit"])
plt.title("Discount vs Profit")
plt.xlabel("Discount")
plt.ylabel("Profit")
plt.show()

"""#📊 Discount vs Profit (Scatter Plot) Summary

This scatter plot shows the relationship between Discount and Profit.

It helps visualize how increasing discounts impact profitability.

A clear pattern often shows that higher discounts lead to lower or negative profit.

Points spread across the graph indicate variations in profit at different discount levels.
"""

#Profit Margin Calculation
df["Profit Margin"] = df["Profit"] / df["Sales"]

df.groupby("Category")["Profit Margin"].mean().plot(kind="bar")
plt.title("Average Profit Margin by Category")
plt.ylabel("Profit Margin")
plt.show()

"""#📊 Profit Margin Analysis Summary

This analysis calculates the Profit Margin (Profit divided by Sales) and visualizes the average profit margin by category.

It shows how much profit is earned for each unit of sales in different categories.

Categories with higher profit margins indicate better efficiency and profitability per sale.

Lower profit margins may suggest higher costs or excessive discounting.
"""

#Region-wise Profit Margin
region_margin = df.groupby("Region").apply(lambda x: x["Profit"].sum()/x["Sales"].sum())

region_margin.plot(kind="bar")
plt.title("Profit Margin by Region")
plt.ylabel("Profit Margin")
plt.show()

"""#📊 Region-wise Profit Margin Summary

This analysis calculates the profit margin for each region by comparing total profit to total sales.

It helps identify which regions are more efficient in generating profit from sales.

Regions with higher profit margins indicate better cost control and pricing strategies.

Lower profit margins may suggest issues like high discounts or operational inefficiencies.

### 📊 Overall Project Summary (Detailed)

This project analyzes the Sample Superstore dataset to evaluate business performance across sales, profit, customer segments, regions, and product categories. The analysis shows that while the company generates strong sales, profitability is inconsistent due to factors such as high discounts and varying performance across regions and product types.

Key insights reveal that certain categories and sub-categories contribute significantly to revenue, but not all are equally profitable. Regional analysis highlights differences in performance, with some areas generating higher profit margins than others. Customer segment analysis indicates which groups drive the most revenue.

A major finding is the negative impact of high discounts on profit, often leading to losses despite high sales. Visualizations and correlation analysis further support these observations by identifying patterns, outliers, and relationships between variables.

Overall, the study emphasizes the importance of optimizing discount strategies, focusing on high-performing products and regions, and improving cost efficiency to enhance overall profitability and support better business decision-making.
"""

